### ISSUE TITLE
Markbot Offline Website Error

### ISSUE THREAD

**Issue by JessJodoin** [JessJodoin/components-on-a-grid#1]
Hey @thomasjbradley

Myself, and another student, keep getting this Markbot error even though everything is linked to git properly. It's also the only repo I've had this issue with for this course.

How do I go about fixing it?

<img width="804" alt="Screen Shot 2020-09-12 at 9 27 01 PM" src="https://user-images.githubusercontent.com/43217543/93008144-73a29100-f53f-11ea-87b7-033a15c0959c.png">

Thanks a bunch!

**Comment by thomasjbradley** [comment]
Totally my fault. I forgot to set it up for hosting.

If you go into the repository on GitHub’s website, go to the "Settings" tab and enable "GitHub Pages" on your `master` branch.

*It’s fixed for all people who have not cloned it. But everyone who has cloned will need to make this update.*
